package authentication

import (
	"time"

	"github.com/yusufwira/lern-golang-gin/entity/dbo/pihc"
	"github.com/yusufwira/lern-golang-gin/entity/mobile/events"
)

type ValidasiEvent struct {
	ID       int    `json:"id"`
	Nik      int    `json:"nik" binding:"required"`
	Title    string `json:"title" binding:"required"`
	Desc     string `json:"desc"`
	Type     string `json:"type" binding:"required"`
	URL      string `json:"url"`
	Location string `json:"location"`
	Image    string `json:"image"`
	Start    string `json:"start" binding:"required"`
	End      string `json:"end" binding:"required"`
	IsPublic int    `json:"is_public"`
	Status   string `json:"status" binding:"required"`
	IDRoom   string `json:"id_room"`
	Person   string `json:"person"`
}

type ValidasiUpdateStatusEvent struct {
	Nik        string `form:"nik" binding:"required"`
	EventID    int    `form:"event_id" binding:"required"`
	Status     string `form:"status" binding:"required"`
	Keterangan string `form:"keterangan"`
}

type ValidasiStoreDispose struct {
	Nik     int    `form:"nik" binding:"required"`
	EventID int    `form:"event_id" binding:"required"`
	Dispose string `form:"dispose" binding:"required"`
}

type ValidasiGetDataByNik struct {
	Nik   string `form:"nik" binding:"required"`
	Month int    `form:"month" binding:"required"`
	Year  int    `form:"year" binding:"required"`
}

type ValidasiDeleteEventByID struct {
	Id         int    `form:"id" binding:"required"`
	Keterangan string `form:"keterangan"`
}

type Event struct {
	EventID         int    `json:"event_id"`
	EventTitle      string `json:"event_title"`
	EventDesc       string `json:"event_desc"`
	EventStart      string `json:"event_start"`
	EventEnd        string `json:"event_end"`
	EventURL        string `json:"event_url"`
	EventImgName    string `json:"event_img_name"`
	EventImgURL     string `json:"event_img_url"`
	EventDate       string `json:"event_date"`
	EventTimeStart  string `json:"event_time_start"`
	EventTimeEnd    string `json:"event_time_end"`
	IsAbsent        bool   `json:"is_absent"`
	CompCode        string `json:"comp_code"`
	StatusKehadiran string `json:"status_kehadiran"`
	AssetCompCode   string `json:"asset_comp_code"`
}

type ListEventDelete struct {
	ID              int       `json:"id"`
	EventTitle      string    `json:"event_title"`
	EventDesc       string    `json:"event_desc"`
	EventStart      string    `json:"event_start"`
	EventEnd        string    `json:"event_end"`
	EventType       string    `json:"event_type"`
	EventURL        string    `json:"event_url"`
	EventImgName    string    `json:"event_img_name"`
	EventImgURL     string    `json:"event_img_url"`
	CompCode        string    `json:"comp_code"`
	Status          string    `json:"status"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ApprovalPerson  string    `json:"approval_person"`
	EventRoom       string    `json:"event_room"`
	EventLocation   string    `json:"event_location"`
	EventKeterangan string    `json:"event_keterangan"`
	Person          []Persons `json:"person"`
}

type Persons struct {
	events.EventPerson
	Dispose []Disposes `json:"dispose"`
}

type Disposes struct {
	events.EventPerson
}

type EventDataByNik struct {
	EventID        int            `json:"event_id"`
	EventTitle     string         `json:"event_title"`
	EventDesc      string         `json:"event_desc"`
	EventStart     string         `json:"event_start"`
	EventEnd       string         `json:"event_end"`
	EventType      string         `json:"event_type"`
	EventURL       string         `json:"event_url"`
	EventImgName   string         `json:"event_img_name"`
	EventImgURL    string         `json:"event_img_url"`
	EventDate      string         `json:"event_date"`
	EventTimeStart string         `json:"event_time_start"`
	EventTimeEnd   string         `json:"event_time_end"`
	EventStatus    string         `json:"event_status"`
	EventLocation  string         `json:"event_location"`
	CompCode       string         `json:"comp_code"`
	AssetCompCode  string         `json:"asset_comp_code"`
	BookRoom       *EventBookRoom `json:"book_room"`
}

type EventBookRoom struct {
	events.EventMsterRoom
	Companys pihc.PihcMasterCompany `json:"companys"`
}

type AutoGenerated struct {
	EventID                 int         `json:"event_id"`
	EventTitle              string      `json:"event_title"`
	EventDesc               string      `json:"event_desc"`
	EventStart              string      `json:"event_start"`
	EventDateStart          string      `json:"event_date_start"`
	EventEnd                string      `json:"event_end"`
	EventDateEnd            string      `json:"event_date_end"`
	EventDateFormat         string      `json:"event_date_format"`
	EventType               string      `json:"event_type"`
	EventURL                interface{} `json:"event_url"`
	EventLocation           interface{} `json:"event_location"`
	EventImgName            interface{} `json:"event_img_name"`
	EventImgURL             interface{} `json:"event_img_url"`
	EventDate               string      `json:"event_date"`
	EventTimeStart          string      `json:"event_time_start"`
	EventTimeEnd            string      `json:"event_time_end"`
	EventStatus             string      `json:"event_status"`
	EventCreatedBy          string      `json:"event_created_by"`
	EventCreatedByNik       string      `json:"event_created_by_nik"`
	EventCreatedDeptTitle   string      `json:"event_created_dept_title"`
	EventApprovalPerson     string      `json:"event_approval_person"`
	EventRoom               string      `json:"event_room"`
	EventApprovalPersonName interface{} `json:"event_approval_person_name"`
	CompCode                string      `json:"comp_code"`
	StatusKehadiran         string      `json:"status_kehadiran"`
	Count                   struct {
		CountGuest      int `json:"count_guest"`
		CountHadir      int `json:"count_hadir"`
		CountMenunggu   int `json:"count_menunggu"`
		CountTidakHadir int `json:"count_tidak_hadir"`
	} `json:"count"`
	IsAbsent       bool   `json:"is_absent"`
	AssestCompCode string `json:"assest_comp_code"`
	Person         []struct {
		Nik             string `json:"nik"`
		Nama            string `json:"nama"`
		DeptTitle       string `json:"dept_title"`
		Email           string `json:"email"`
		StatusKehadiran string `json:"status_kehadiran"`
		PhotoURL        string `json:"photo_url"`
	} `json:"person"`
	Notulen  interface{}   `json:"notulen"`
	Materi   []interface{} `json:"materi"`
	BookRoom struct {
		IDBooking    int    `json:"id_booking"`
		CodeRoom     string `json:"code_room"`
		DateStart    string `json:"date_start"`
		DateEnd      string `json:"date_end"`
		TimeStart    string `json:"time_start"`
		TimeEnd      string `json:"time_end"`
		RoomID       string `json:"room_id"`
		RoomName     string `json:"room_name"`
		RoomCategory string `json:"room_category"`
		RoomCompCode string `json:"room_comp_code"`
		RoomCompName string `json:"room_comp_name"`
	} `json:"book_room"`
	TimeCreatedAt string `json:"time_created_at"`
}